const Database = require('better-sqlite3');
const db = new Database('./database/quiz.db');

const questions = [
    // === TARANTO (20 domande) ===
    { text: "In che anno fu fondata Taranto secondo la tradizione?", a: "706 a.C.", b: "753 a.C.", c: "500 a.C.", d: "264 a.C.", correct: "A", category: "taranto" },
    { text: "Taranto fu l'unica colonia di quale città greca?", a: "Atene", b: "Corinto", c: "Sparta", d: "Tebe", correct: "C", category: "taranto" },
    { text: "Come viene chiamata Taranto per la sua posizione geografica?", a: "Città dei ponti", b: "Città dei due mari", c: "Perla del Sud", d: "Regina dello Ionio", correct: "B", category: "taranto" },
    { text: "Chi è il patrono di Taranto?", a: "San Nicola", b: "San Cataldo", c: "Sant'Oronzo", d: "San Domenico", correct: "B", category: "taranto" },
    { text: "Come si chiamavano le isole antistanti Taranto secondo i Greci?", a: "Isole Tremiti", b: "Isole Eolie", c: "Isole Cheradi (Elettridi)", d: "Isole Egadi", correct: "C", category: "taranto" },
    { text: "Secondo la leggenda, chi fondò Taranto cavalcando un delfino?", a: "Ulisse", b: "Taras", c: "Poseidone", d: "Achille", correct: "B", category: "taranto" },
    { text: "Il Tempio Dorico di Taranto a quale divinità era probabilmente dedicato?", a: "Zeus", b: "Poseidone", c: "Una divinità femminile", d: "Apollo", correct: "C", category: "taranto" },
    { text: "In quale secolo fu costruito il Castello Aragonese di Taranto?", a: "XIII secolo", b: "XIV secolo", c: "XV secolo", d: "XVI secolo", correct: "C", category: "taranto" },
    { text: "Cosa ospita il MArTA di Taranto?", a: "Arte moderna", b: "Reperti archeologici", c: "Quadri rinascimentali", d: "Sculture barocche", correct: "B", category: "taranto" },
    { text: "Cosa sono gli 'Ori di Taranto' esposti al MArTA?", a: "Monete antiche", b: "Gioielli del IV-I sec a.C.", c: "Statue dorate", d: "Mosaici dorati", correct: "B", category: "taranto" },
    { text: "Il Principato di Taranto durò dal 1088 fino a quale anno?", a: "1265", b: "1365", c: "1465", d: "1565", correct: "C", category: "taranto" },
    { text: "Quale evento bellico colpì Taranto l'11-12 novembre 1940?", a: "Bombardamento tedesco", b: "Attacco della Royal Navy", c: "Sbarco americano", d: "Battaglia navale italiana", correct: "B", category: "taranto" },
    { text: "Quale famoso compositore nacque a Taranto nel 1740?", a: "Rossini", b: "Verdi", c: "Giovanni Paisiello", d: "Puccini", correct: "C", category: "taranto" },
    { text: "Archita di Taranto fu un famoso:", a: "Gladiatore", b: "Condottiero e filosofo", c: "Imperatore", d: "Poeta", correct: "B", category: "taranto" },
    { text: "Di quale regno era capitale la Magna Grecia con Taranto?", a: "Regno di Sicilia", b: "Città-stato greche del Sud Italia", c: "Impero Romano", d: "Regno di Napoli", correct: "B", category: "taranto" },
    { text: "Come si chiama il mare interno di Taranto?", a: "Mar Grande", b: "Mar Piccolo", c: "Mar Ionio", d: "Mar Adriatico", correct: "B", category: "taranto" },
    { text: "Quale scuola filosofica aveva sede a Taranto?", a: "Epicurea", b: "Stoica", c: "Pitagorica", d: "Platonica", correct: "C", category: "taranto" },
    { text: "La Cattedrale di San Cataldo è la più antica cattedrale romanica di quale regione?", a: "Calabria", b: "Campania", c: "Puglia", d: "Basilicata", correct: "C", category: "taranto" },
    { text: "Il Castello Aragonese di Taranto appartiene oggi a:", a: "Il Comune", b: "La Regione", c: "La Marina Militare", d: "Un privato", correct: "C", category: "taranto" },
    { text: "Quante isole formano l'arcipelago delle Cheradi?", a: "2", b: "3", c: "4", d: "5", correct: "B", category: "taranto" },

    // === PUGLIA (25 domande) ===
    { text: "Quale città pugliese è famosa per i suoi Trulli?", a: "Lecce", b: "Bari", c: "Alberobello", d: "Ostuni", correct: "C", category: "puglia" },
    { text: "Come viene chiamata Lecce per il suo stile architettonico?", a: "Città del Rinascimento", b: "Città del Barocco", c: "Città del Gotico", d: "Città del Romanico", correct: "B", category: "puglia" },
    { text: "Quale fortezza pugliese fu costruita da Federico II di Svevia?", a: "Castel del Monte", b: "Castello Svevo di Bari", c: "Castello di Trani", d: "Castello di Otranto", correct: "A", category: "puglia" },
    { text: "Qual è la forma architettonica di Castel del Monte?", a: "Quadrata", b: "Circolare", c: "Ottagonale", d: "Esagonale", correct: "C", category: "puglia" },
    { text: "Come vengono chiamate le città bianche della Puglia?", a: "Città candide", b: "Città bianche", c: "Borghi bianchi", d: "Paesi imbiancati", correct: "B", category: "puglia" },
    { text: "Perché le facciate delle città pugliesi erano dipinte di bianco?", a: "Per estetica", b: "Per protezione da epidemie", c: "Per tradizione religiosa", d: "Per risparmiare", correct: "B", category: "puglia" },
    { text: "Quale città pugliese è il punto più a est d'Italia?", a: "Brindisi", b: "Lecce", c: "Otranto", d: "Gallipoli", correct: "C", category: "puglia" },
    { text: "Come viene chiamata Otranto?", a: "Città dei Santi", b: "Città dei Martiri", c: "Città degli Eroi", d: "Città della Fede", correct: "B", category: "puglia" },
    { text: "Chi è il santo patrono di Bari?", a: "San Cataldo", b: "Sant'Oronzo", c: "San Nicola", d: "San Michele", correct: "C", category: "puglia" },
    { text: "Quando si festeggia San Nicola a Bari?", a: "6 gennaio", b: "6 dicembre", c: "15 agosto", d: "25 aprile", correct: "B", category: "puglia" },
    { text: "Cos'è la Taranta?", a: "Un piatto tipico", b: "Una danza tradizionale", c: "Un vino", d: "Un formaggio", correct: "B", category: "puglia" },
    { text: "Quale città pugliese ospita uno dei carnevali più famosi d'Italia?", a: "Bari", b: "Foggia", c: "Putignano", d: "Lecce", correct: "C", category: "puglia" },
    { text: "Quale santuario UNESCO si trova a Monte Sant'Angelo?", a: "San Nicola", b: "San Michele Arcangelo", c: "Santa Maria", d: "San Pietro", correct: "B", category: "puglia" },
    { text: "I Trulli di Alberobello sono costruiti con:", a: "Mattoni", b: "Pietra senza malta", c: "Cemento", d: "Legno", correct: "B", category: "puglia" },
    { text: "In quale valle si trovano principalmente i Trulli?", a: "Valle dei Templi", b: "Val d'Orcia", c: "Valle d'Itria", d: "Valle dei Mulini", correct: "C", category: "puglia" },
    { text: "Quale comunità linguistica storica vive in Puglia?", a: "Catalana", b: "Grika", c: "Basca", d: "Bretone", correct: "B", category: "puglia" },
    { text: "Quale dolce pugliese è tipico del Natale?", a: "Panettone", b: "Cartellate", c: "Pandoro", d: "Colomba", correct: "B", category: "puglia" },
    { text: "Cosa sono le Pucce dell'Immacolata?", a: "Dolci", b: "Pane tipico", c: "Pasta", d: "Formaggi", correct: "B", category: "puglia" },
    { text: "Come si chiamano gli ulivi secolari della Puglia?", a: "Ulivi antichi", b: "Ulivi millenari", c: "Ulivi sacri", d: "Ulivi giganti", correct: "B", category: "puglia" },
    { text: "Quale santuario si trova a Santa Maria di Leuca?", a: "Finibus Terrae", b: "Mare Nostrum", c: "Terra Santa", d: "Luce Eterna", correct: "A", category: "puglia" },
    { text: "Ostuni è chiamata anche:", a: "Città rosa", b: "Città bianca", c: "Città d'oro", d: "Città verde", correct: "B", category: "puglia" },
    { text: "Quanti siti UNESCO ha la Puglia?", a: "1", b: "2", c: "3", d: "4", correct: "C", category: "puglia" },
    { text: "Il Castello Normanno Svevo si trova a:", a: "Lecce", b: "Bari", c: "Taranto", d: "Foggia", correct: "B", category: "puglia" },
    { text: "Quale strumento accompagna la Taranta?", a: "Violino", b: "Tamburello", c: "Pianoforte", d: "Arpa", correct: "B", category: "puglia" },
    { text: "Cosa sono le Tavole di San Giuseppe?", a: "Mobili antichi", b: "Tradizione religiosa con cibo", c: "Quadri sacri", d: "Libri liturgici", correct: "B", category: "puglia" },

    // === ITALIA (40 domande) ===
    { text: "Qual è la capitale d'Italia?", a: "Milano", b: "Roma", c: "Napoli", d: "Firenze", correct: "B", category: "italia" },
    { text: "Quante regioni ha l'Italia?", a: "18", b: "19", c: "20", d: "21", correct: "C", category: "italia" },
    { text: "Qual è il fiume più lungo d'Italia?", a: "Tevere", b: "Adige", c: "Po", d: "Arno", correct: "C", category: "italia" },
    { text: "Qual è la montagna più alta d'Italia?", a: "Monte Rosa", b: "Monte Bianco", c: "Cervino", d: "Gran Paradiso", correct: "B", category: "italia" },
    { text: "In che anno è nata la Repubblica Italiana?", a: "1945", b: "1946", c: "1947", d: "1948", correct: "B", category: "italia" },
    { text: "Quale isola italiana è la più grande del Mediterraneo?", a: "Sardegna", b: "Sicilia", c: "Elba", d: "Capri", correct: "B", category: "italia" },
    { text: "Chi scrisse la Divina Commedia?", a: "Petrarca", b: "Boccaccio", c: "Dante Alighieri", d: "Manzoni", correct: "C", category: "italia" },
    { text: "In quale città si trova il Colosseo?", a: "Napoli", b: "Roma", c: "Milano", d: "Venezia", correct: "B", category: "italia" },
    { text: "Quale città italiana è famosa per i suoi canali?", a: "Firenze", b: "Genova", c: "Venezia", d: "Trieste", correct: "C", category: "italia" },
    { text: "Chi dipinse la Cappella Sistina?", a: "Leonardo", b: "Raffaello", c: "Michelangelo", d: "Caravaggio", correct: "C", category: "italia" },
    { text: "Qual è il patrono d'Italia?", a: "San Pietro", b: "San Francesco", c: "San Paolo", d: "San Marco", correct: "B", category: "italia" },
    { text: "In quale regione si trova la Torre di Pisa?", a: "Lombardia", b: "Toscana", c: "Emilia-Romagna", d: "Liguria", correct: "B", category: "italia" },
    { text: "Quale vulcano si trova vicino a Napoli?", a: "Etna", b: "Stromboli", c: "Vesuvio", d: "Vulcano", correct: "C", category: "italia" },
    { text: "Chi inventò la radio?", a: "Volta", b: "Marconi", c: "Meucci", d: "Fermi", correct: "B", category: "italia" },
    { text: "Quale città ospita la Scala?", a: "Roma", b: "Torino", c: "Milano", d: "Venezia", correct: "C", category: "italia" },
    { text: "In che anno l'Italia vinse i Mondiali di calcio per l'ultima volta?", a: "1982", b: "1990", c: "2006", d: "2010", correct: "C", category: "italia" },
    { text: "Quale lago italiano è il più grande?", a: "Como", b: "Maggiore", c: "Garda", d: "Trasimeno", correct: "C", category: "italia" },
    { text: "Chi fu il primo presidente della Repubblica Italiana?", a: "De Gasperi", b: "Einaudi", c: "De Nicola", d: "Gronchi", correct: "C", category: "italia" },
    { text: "Quale regione italiana produce più vino?", a: "Toscana", b: "Piemonte", c: "Veneto", d: "Sicilia", correct: "C", category: "italia" },
    { text: "In quale città nacque Cristoforo Colombo?", a: "Venezia", b: "Genova", c: "Napoli", d: "Pisa", correct: "B", category: "italia" },
    { text: "Qual è il simbolo della Repubblica Italiana?", a: "Aquila", b: "Leone", c: "Stella", d: "Quercia", correct: "C", category: "italia" },
    { text: "Chi compose l'inno nazionale italiano?", a: "Verdi", b: "Mameli", c: "Rossini", d: "Puccini", correct: "B", category: "italia" },
    { text: "Quante stelle ha la bandiera dell'Unione Europea?", a: "10", b: "12", c: "15", d: "27", correct: "B", category: "italia" },
    { text: "In quale anno l'Italia adottò l'Euro?", a: "1999", b: "2000", c: "2001", d: "2002", correct: "D", category: "italia" },
    { text: "Quale città italiana ospitò le Olimpiadi invernali nel 2006?", a: "Milano", b: "Torino", c: "Cortina", d: "Bolzano", correct: "B", category: "italia" },
    { text: "Chi scrisse 'I Promessi Sposi'?", a: "Verga", b: "Manzoni", c: "Pirandello", d: "Svevo", correct: "B", category: "italia" },
    { text: "Quale scienziato italiano inventò la pila?", a: "Galileo", b: "Fermi", c: "Volta", d: "Marconi", correct: "C", category: "italia" },
    { text: "In quale regione si trova la Costiera Amalfitana?", a: "Calabria", b: "Campania", c: "Puglia", d: "Sicilia", correct: "B", category: "italia" },
    { text: "Quale città è capoluogo della Lombardia?", a: "Bergamo", b: "Brescia", c: "Milano", d: "Monza", correct: "C", category: "italia" },
    { text: "Chi fu l'ultimo re d'Italia?", a: "Vittorio Emanuele II", b: "Umberto I", c: "Vittorio Emanuele III", d: "Umberto II", correct: "D", category: "italia" },
    { text: "In quale anno fu unificata l'Italia?", a: "1848", b: "1861", c: "1870", d: "1918", correct: "B", category: "italia" },
    { text: "Quale mare bagna la Liguria?", a: "Adriatico", b: "Tirreno", c: "Ionio", d: "Ligure", correct: "D", category: "italia" },
    { text: "Chi dipinse 'La nascita di Venere'?", a: "Leonardo", b: "Botticelli", c: "Raffaello", d: "Tiziano", correct: "B", category: "italia" },
    { text: "Quale città italiana è famosa per il Palio?", a: "Firenze", b: "Siena", c: "Pisa", d: "Lucca", correct: "B", category: "italia" },
    { text: "Quanti abitanti ha circa l'Italia?", a: "50 milioni", b: "59 milioni", c: "65 milioni", d: "70 milioni", correct: "B", category: "italia" },
    { text: "Quale regione confina con la Svizzera e l'Austria?", a: "Piemonte", b: "Lombardia", c: "Trentino-Alto Adige", d: "Friuli", correct: "C", category: "italia" },
    { text: "In quale città si trova la Fontana di Trevi?", a: "Napoli", b: "Roma", c: "Firenze", d: "Venezia", correct: "B", category: "italia" },
    { text: "Quale famoso esploratore italiano viaggiò in Cina?", a: "Colombo", b: "Vespucci", c: "Marco Polo", d: "Caboto", correct: "C", category: "italia" },
    { text: "Chi fu Giuseppe Garibaldi?", a: "Un pittore", b: "Un musicista", c: "Un condottiero", d: "Un poeta", correct: "C", category: "italia" },
    { text: "Quale regione italiana è la più piccola?", a: "Molise", b: "Valle d'Aosta", c: "Liguria", d: "Umbria", correct: "B", category: "italia" },

    // === CULTURA GENERALE (70 domande) ===
    { text: "Qual è il pianeta più grande del Sistema Solare?", a: "Saturno", b: "Giove", c: "Nettuno", d: "Urano", correct: "B", category: "generale" },
    { text: "Chi scrisse 'Romeo e Giulietta'?", a: "Dante", b: "Shakespeare", c: "Molière", d: "Goethe", correct: "B", category: "generale" },
    { text: "Qual è l'elemento chimico con simbolo 'O'?", a: "Oro", b: "Osmio", c: "Ossigeno", d: "Oganesson", correct: "C", category: "generale" },
    { text: "In che anno iniziò la Seconda Guerra Mondiale?", a: "1938", b: "1939", c: "1940", d: "1941", correct: "B", category: "generale" },
    { text: "Qual è la capitale della Francia?", a: "Lione", b: "Marsiglia", c: "Parigi", d: "Nizza", correct: "C", category: "generale" },
    { text: "Chi dipinse la Gioconda?", a: "Michelangelo", b: "Raffaello", c: "Leonardo da Vinci", d: "Caravaggio", correct: "C", category: "generale" },
    { text: "Quanti continenti esistono?", a: "5", b: "6", c: "7", d: "8", correct: "C", category: "generale" },
    { text: "Qual è l'oceano più grande del mondo?", a: "Atlantico", b: "Indiano", c: "Pacifico", d: "Artico", correct: "C", category: "generale" },
    { text: "Chi inventò la lampadina?", a: "Tesla", b: "Edison", c: "Bell", d: "Morse", correct: "B", category: "generale" },
    { text: "Qual è la capitale del Giappone?", a: "Osaka", b: "Kyoto", c: "Tokyo", d: "Hiroshima", correct: "C", category: "generale" },
    { text: "Quanti lati ha un esagono?", a: "5", b: "6", c: "7", d: "8", correct: "B", category: "generale" },
    { text: "Chi fu il primo uomo sulla Luna?", a: "Buzz Aldrin", b: "Neil Armstrong", c: "Yuri Gagarin", d: "John Glenn", correct: "B", category: "generale" },
    { text: "Qual è il fiume più lungo del mondo?", a: "Nilo", b: "Amazzoni", c: "Mississipi", d: "Gange", correct: "A", category: "generale" },
    { text: "In che anno cadde il Muro di Berlino?", a: "1987", b: "1988", c: "1989", d: "1990", correct: "C", category: "generale" },
    { text: "Qual è la moneta degli Stati Uniti?", a: "Euro", b: "Sterlina", c: "Dollaro", d: "Yen", correct: "C", category: "generale" },
    { text: "Chi scrisse 'Cento anni di solitudine'?", a: "Borges", b: "García Márquez", c: "Neruda", d: "Allende", correct: "B", category: "generale" },
    { text: "Qual è il simbolo chimico dell'oro?", a: "Or", b: "Go", c: "Au", d: "Ag", correct: "C", category: "generale" },
    { text: "Quante corde ha una chitarra classica?", a: "4", b: "5", c: "6", d: "7", correct: "C", category: "generale" },
    { text: "Chi è l'autore di 'Harry Potter'?", a: "Stephen King", b: "J.K. Rowling", c: "Tolkien", d: "C.S. Lewis", correct: "B", category: "generale" },
    { text: "Qual è la capitale della Spagna?", a: "Barcellona", b: "Madrid", c: "Siviglia", d: "Valencia", correct: "B", category: "generale" },
    { text: "Quanti giocatori ci sono in una squadra di calcio?", a: "9", b: "10", c: "11", d: "12", correct: "C", category: "generale" },
    { text: "Chi compose la Nona Sinfonia?", a: "Mozart", b: "Bach", c: "Beethoven", d: "Vivaldi", correct: "C", category: "generale" },
    { text: "Qual è il paese più grande del mondo?", a: "Canada", b: "Cina", c: "USA", d: "Russia", correct: "D", category: "generale" },
    { text: "Quanti denti ha un adulto?", a: "28", b: "30", c: "32", d: "34", correct: "C", category: "generale" },
    { text: "Chi scoprì la penicillina?", a: "Pasteur", b: "Fleming", c: "Koch", d: "Jenner", correct: "B", category: "generale" },
    { text: "Qual è la capitale dell'Australia?", a: "Sydney", b: "Melbourne", c: "Canberra", d: "Perth", correct: "C", category: "generale" },
    { text: "Quanti anni dura un secolo?", a: "10", b: "50", c: "100", d: "1000", correct: "C", category: "generale" },
    { text: "Chi dipinse 'La notte stellata'?", a: "Monet", b: "Van Gogh", c: "Picasso", d: "Dalí", correct: "B", category: "generale" },
    { text: "Qual è il metallo più prezioso?", a: "Argento", b: "Platino", c: "Oro", d: "Rodio", correct: "D", category: "generale" },
    { text: "In che anno fu fondata Roma secondo la leggenda?", a: "753 a.C.", b: "509 a.C.", c: "27 a.C.", d: "476 d.C.", correct: "A", category: "generale" },
    { text: "Qual è l'animale più veloce del mondo?", a: "Leone", b: "Ghepardo", c: "Falco pellegrino", d: "Leopardo", correct: "C", category: "generale" },
    { text: "Chi scrisse 'L'Odissea'?", a: "Virgilio", b: "Omero", c: "Ovidio", d: "Sofocle", correct: "B", category: "generale" },
    { text: "Quante ossa ha il corpo umano adulto?", a: "186", b: "206", c: "226", d: "246", correct: "B", category: "generale" },
    { text: "Qual è la lingua più parlata al mondo?", a: "Inglese", b: "Spagnolo", c: "Cinese mandarino", d: "Hindi", correct: "C", category: "generale" },
    { text: "Chi inventò il telefono?", a: "Edison", b: "Meucci", c: "Bell", d: "Marconi", correct: "B", category: "generale" },
    { text: "Qual è la capitale del Brasile?", a: "Rio de Janeiro", b: "São Paulo", c: "Brasilia", d: "Salvador", correct: "C", category: "generale" },
    { text: "Quanti gradi ha un angolo retto?", a: "45", b: "90", c: "180", d: "360", correct: "B", category: "generale" },
    { text: "Chi fu il primo imperatore romano?", a: "Giulio Cesare", b: "Augusto", c: "Nerone", d: "Traiano", correct: "B", category: "generale" },
    { text: "Qual è il gas più abbondante nell'atmosfera?", a: "Ossigeno", b: "Anidride carbonica", c: "Azoto", d: "Argon", correct: "C", category: "generale" },
    { text: "Chi scrisse '1984'?", a: "Huxley", b: "Orwell", c: "Bradbury", d: "Asimov", correct: "B", category: "generale" },
    { text: "Qual è la capitale della Germania?", a: "Monaco", b: "Amburgo", c: "Berlino", d: "Francoforte", correct: "C", category: "generale" },
    { text: "Quanti colori ha l'arcobaleno?", a: "5", b: "6", c: "7", d: "8", correct: "C", category: "generale" },
    { text: "Chi compose 'Le quattro stagioni'?", a: "Bach", b: "Mozart", c: "Vivaldi", d: "Händel", correct: "C", category: "generale" },
    { text: "Qual è il mammifero più grande del mondo?", a: "Elefante", b: "Balena azzurra", c: "Orca", d: "Squalo bianco", correct: "B", category: "generale" },
    { text: "In che anno scoppiò la Rivoluzione Francese?", a: "1776", b: "1789", c: "1799", d: "1804", correct: "B", category: "generale" },
    { text: "Qual è la valuta del Regno Unito?", a: "Euro", b: "Dollaro", c: "Sterlina", d: "Franco", correct: "C", category: "generale" },
    { text: "Chi dipinse 'L'ultima cena'?", a: "Michelangelo", b: "Raffaello", c: "Leonardo da Vinci", d: "Giotto", correct: "C", category: "generale" },
    { text: "Quanti sono i sensi umani tradizionali?", a: "4", b: "5", c: "6", d: "7", correct: "B", category: "generale" },
    { text: "Qual è la capitale del Canada?", a: "Toronto", b: "Montreal", c: "Vancouver", d: "Ottawa", correct: "D", category: "generale" },
    { text: "Chi formulò la teoria della relatività?", a: "Newton", b: "Einstein", c: "Hawking", d: "Galileo", correct: "B", category: "generale" },
    { text: "Quanti pianeti ci sono nel Sistema Solare?", a: "7", b: "8", c: "9", d: "10", correct: "B", category: "generale" },
    { text: "Qual è il deserto più grande del mondo?", a: "Sahara", b: "Gobi", c: "Antartide", d: "Arabico", correct: "C", category: "generale" },
    { text: "Chi scrisse 'Il Piccolo Principe'?", a: "Verne", b: "Saint-Exupéry", c: "Hugo", d: "Dumas", correct: "B", category: "generale" },
    { text: "Qual è il punto più alto della Terra?", a: "K2", b: "Monte Bianco", c: "Everest", d: "Aconcagua", correct: "C", category: "generale" },
    { text: "Quante facce ha un cubo?", a: "4", b: "6", c: "8", d: "12", correct: "B", category: "generale" },
    { text: "Chi fu il fondatore di Apple?", a: "Bill Gates", b: "Steve Jobs", c: "Jeff Bezos", d: "Mark Zuckerberg", correct: "B", category: "generale" },
    { text: "Qual è la capitale dell'Egitto?", a: "Alessandria", b: "Luxor", c: "Il Cairo", d: "Giza", correct: "C", category: "generale" },
    { text: "Quanti cuori ha un polpo?", a: "1", b: "2", c: "3", d: "4", correct: "C", category: "generale" },
    { text: "Chi scrisse 'Don Chisciotte'?", a: "Lope de Vega", b: "Cervantes", c: "Calderón", d: "Góngora", correct: "B", category: "generale" },
    { text: "Qual è il paese più popoloso del mondo?", a: "USA", b: "India", c: "Cina", d: "Indonesia", correct: "B", category: "generale" },
    { text: "In che anno l'uomo sbarcò sulla Luna?", a: "1967", b: "1968", c: "1969", d: "1970", correct: "C", category: "generale" },
    { text: "Qual è la capitale della Russia?", a: "San Pietroburgo", b: "Mosca", c: "Kiev", d: "Novosibirsk", correct: "B", category: "generale" },
    { text: "Chi dipinse 'Guernica'?", a: "Dalí", b: "Miró", c: "Picasso", d: "Goya", correct: "C", category: "generale" },
    { text: "Quante settimane ha un anno?", a: "48", b: "50", c: "52", d: "54", correct: "C", category: "generale" },
    { text: "Qual è il simbolo chimico del ferro?", a: "Fr", b: "Fe", c: "Fi", d: "Fo", correct: "B", category: "generale" },
    { text: "Chi inventò la stampa a caratteri mobili?", a: "Da Vinci", b: "Gutenberg", c: "Galileo", d: "Copernico", correct: "B", category: "generale" },
    { text: "Qual è la capitale della Grecia?", a: "Salonicco", b: "Atene", c: "Patrasso", d: "Creta", correct: "B", category: "generale" },
    { text: "Quanti emisferi ha il cervello umano?", a: "1", b: "2", c: "3", d: "4", correct: "B", category: "generale" },
    { text: "Chi compose 'Il barbiere di Siviglia'?", a: "Verdi", b: "Puccini", c: "Rossini", d: "Donizetti", correct: "C", category: "generale" },
    { text: "Qual è il colore del rubino?", a: "Blu", b: "Verde", c: "Rosso", d: "Giallo", correct: "C", category: "generale" }
];

const insertStmt = db.prepare(`
    INSERT INTO questions (text, option_a, option_b, option_c, option_d, correct_answer, category)
    VALUES (?, ?, ?, ?, ?, ?, ?)
`);

let inserted = 0;
for (const q of questions) {
    try {
        insertStmt.run(q.text, q.a, q.b, q.c, q.d, q.correct, q.category);
        inserted++;
    } catch (err) {
        console.log('Saltata (duplicato?):', q.text.substring(0, 50));
    }
}

console.log(`Inserite ${inserted} domande su ${questions.length}`);

// Conta totale
const count = db.prepare('SELECT COUNT(*) as count FROM questions').get();
console.log(`Totale domande nel database: ${count.count}`);

db.close();
